name: Test 

on:
  create:
  milestone:
    types: [closed]
  push: 
    branches:
      - main 

jobs:
  test:
    name: Test
    runs-on: ub22
    steps:
      - name: Get the sources
        uses: actions/checkout@v1

      - name: Create a release draft for a milestone 
        id: create-release-draft
        uses: ./
        with:
          repo-token: ${{ secrets.CM_GITHUB_TOKEN }}

      - name: Print the URL of the release draft 
        if: steps.create-release-draft.outputs.release-url != ''
        run: echo ${{ steps.create-release-draft.outputs.release-url }}
